package test.model;

public class Login {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.uId
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.uName
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.uPwd
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    private String upwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.uId
     *
     * @return the value of login.uId
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.uId
     *
     * @param uid the value for login.uId
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.uName
     *
     * @return the value of login.uName
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.uName
     *
     * @param uname the value for login.uName
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.uPwd
     *
     * @return the value of login.uPwd
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.uPwd
     *
     * @param upwd the value for login.uPwd
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }
}