package test.dao;

import test.model.Login;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Wed Jul 12 10:10:28 CST 2017
     */
    int insertSelective(Login record);
}